---
builds:
  - id: twt
    binary: twt
    main: ./cmd/twt
    flags: -tags "static_build"
    ldflags: -w -X github.com/prologic/twtxt.Version={{.Version}} -X github.com/prologic/twtxt.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - i386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
signs:
  - artifacts: checksum
brews:
  -
    github:
      owner: prologic
      name: homebrew-twtxt
    homepage: "https://github.io/prologic/twtxt"
    description: |
      📕 twtxt is a Self-Hosted, Twitter™-like Decentralised microBlogging
      platform. No ads, no tracking, your content, your data!
release:
  github:
    owner: prologic
    name: twtxt
  draft: true
